name = "fifo-crypto-calculator"
compatibility_date = "2024-03-20"

[site]
bucket = "./public"

[build]
command = "npm run build"
upload.format = "service-worker"

[env.production]
workers_dev = true

[pages]
build_output_dir = "dist" 